name: Compile TWRP
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      USE_CCACHE: "1"
      CCACHE_EXEC: "/usr/bin/ccache"
    steps:
      - name: Configure
        run: |
          curl https://storage.googleapis.com/git-repo-downloads/repo | sudo tee /usr/bin/repo > /dev/null
          sudo ln -sf /usr/bin/python3 /usr/bin/python
          sudo chmod +x /usr/bin/repo
          sudo apt install -yq bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev libwxgtk3.0-dev python3
          git config --global user.email "116288337+freedomSymbol@users.noreply.github.com"
          git config --global user.name "freedomSymbol@bot"
      - name: Get source
        run: |
          mkdir $GITHUB_WORKSPACE/twrp
          cd $GITHUB_WORKSPACE/twrp
          repo init --depth=1 -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git -b twrp-7.1
          repo sync -c -f --no-tags --no-clone-bundle -j16
      - name: Setup device
        uses: actions/checkout@v3
        with:
          path: 'twrp/device/Xiaoxun/MiKidsWatch_F3'   
      - name: Build
        run: |
          sudo rm -f /usr/bin/python
          sudo apt install -yq python-minimal
          sudo ln -sf /usr/bin/python2 /usr/bin/python
          cd $GITHUB_WORKSPACE/twrp
          source build/envsetup.sh
          croot
          lunch omni_MiKidsWatch_F3-eng
          mka -j$(nproc --all) recoveryimage
      - name: Package image
        run: |
          export version=$(cat twrp/bootable/recovery/variables.h | grep "define TW_MAIN_VERSION_STR" | cut -d '"' -f2)
          cp twrp/out/target/product/MiKidsWatch_F3/recovery.img twrp-${version}_0-MiKidsWatch_F3.img
      - uses: actions/upload-artifact@v3
        with:
          name: TWRP Image
          path: 'twrp-*.img'
